#ifndef PATHFINDING_ERROR_H
#define PATHFINDING_ERROR_H

#define PATHFINDING_ERROR_NONE 0
#define PATHFINDING_ERROR_PATH_NOT_FOUND 1
#define PATHFINDING_ERROR_WRONG_INPUTS 2
#define PATHFINDING_ERROR_NOT_ENOUGH_CACHE 3

#define PATHFINDING_ERROR_UNDEFINED 255

#endif